'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/use-auth';
import Image from 'next/image';
import UserLayout from '@/components/UserLayout';

type AnalysisType = 'Intraday Trading' | 'Positional Trading' | 'Swing Trading';

const AnalysisPageContent: React.FC = () => {
  const router = useRouter();
  const { user } = useAuth();
  const [analysisType, setAnalysisType] = useState<AnalysisType | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');
  const [preview, setPreview] = useState<string>('');
  
  // Pricing for different analysis types
  const pricing = {
    'Intraday Trading': 10,
    'Positional Trading': 15,
    'Swing Trading': 20
  };
  
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      // Check if file is an image
      if (!selectedFile.type.startsWith('image/')) {
        setError('Please upload an image file');
        setFile(null);
        setPreview('');
        return;
      }
      
      setFile(selectedFile);
      setError('');
      
      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setPreview(e.target?.result as string);
      };
      reader.readAsDataURL(selectedFile);
    }
  };
  
  const handleAnalysisTypeSelect = (type: AnalysisType) => {
    setAnalysisType(type);
  };
  
  // Check user access on component mount and when user changes
  React.useEffect(() => {
    if (typeof window !== 'undefined' && user?.id) {
      const storedData = localStorage.getItem('stock_analysis_db');
      if (storedData) {
        const parsedData = JSON.parse(storedData);
        const currentUser = parsedData.users.find((u: { id: string }) => u.id === user.id);
        
        if (currentUser) {
          // Check if there's an inconsistency between conditions and access flag
          const hasTrialAccess = currentUser.analysis_count < 5;
          const hasWalletBalance = currentUser.wallet_balance > 0;
          const shouldHaveAccess = hasTrialAccess || hasWalletBalance;
          
          // If user should have access but access is disabled, enable it
          if (shouldHaveAccess && !currentUser.stock_analysis_access) {
            currentUser.stock_analysis_access = true;
            localStorage.setItem('stock_analysis_db', JSON.stringify(parsedData));
          }
          
          // If user shouldn't have access but access is enabled, disable it
          if (!shouldHaveAccess && currentUser.stock_analysis_access) {
            currentUser.stock_analysis_access = false;
            localStorage.setItem('stock_analysis_db', JSON.stringify(parsedData));
          }
        }
      }
    }
  }, [user]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!analysisType) {
      setError('Please select an analysis type');
      return;
    }
    
    if (!file) {
      setError('Please upload a stock market graph image');
      return;
    }
    
    setLoading(true);
    setError('');
    
    try {
      // In a real implementation, this would upload the file to a server
      // and process the analysis with AI
      
      // For now, we'll simulate the process with localStorage
      if (typeof window !== 'undefined') {
        const storedData = localStorage.getItem('stock_analysis_db');
        if (storedData) {
          const parsedData = JSON.parse(storedData);
          const currentUser = parsedData.users.find((u: { id: string }) => u.id === user?.id);
          
          if (currentUser) {
            // Check if user has access
            const hasTrialAccess = currentUser.analysis_count < 5;
            const hasWalletBalance = currentUser.wallet_balance > 0;
            
            if (!hasTrialAccess && !hasWalletBalance) {
              setError('You have no access to analysis. Please top up your wallet.');
              setLoading(false);
              return;
            }
            
            // Create a new analysis entry
            const newAnalysis = {
              id: `analysis_${Date.now()}`,
              analysis_type: analysisType,
              stock_name: 'Sample Stock', // In a real app, user would input this
              analysis_result: 'This is a sample analysis result. In a real application, this would be generated by AI based on the uploaded image.',
              image_path: preview, // In a real app, this would be a path to the stored image
              created_at: new Date().toISOString()
            };
            
            // Update user's analysis history
            if (!currentUser.analysis_history) {
              currentUser.analysis_history = [];
            }
            currentUser.analysis_history.unshift(newAnalysis);
            
            // Update analysis count and wallet balance
            currentUser.analysis_count += 1;
            
            // If trial is used up, deduct from wallet
            if (currentUser.analysis_count > 5) {
              const price = pricing[analysisType];
              currentUser.wallet_balance -= price;
              
              // Ensure wallet balance doesn't go below 0
              if (currentUser.wallet_balance < 0) {
                currentUser.wallet_balance = 0;
              }
            }
            
            // Update access flags based on new state
            const stillHasTrialAccess = currentUser.analysis_count < 5;
            const stillHasWalletBalance = currentUser.wallet_balance > 0;
            currentUser.stock_analysis_access = stillHasTrialAccess || stillHasWalletBalance;
            currentUser.trial_expiry = currentUser.analysis_count >= 5;
            
            // Save updated data
            localStorage.setItem('stock_analysis_db', JSON.stringify(parsedData));
            
            // Redirect to dashboard
            setTimeout(() => {
              router.push('/dashboard');
            }, 1000);
          }
        }
      }
    } catch (error) {
      console.error('Error processing analysis:', error);
      setError('An error occurred while processing your analysis. Please try again.');
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <div className="container mx-auto py-6 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 shadow overflow-hidden sm:rounded-lg">
          <div className="px-4 py-5 sm:px-6">
            <h3 className="text-lg leading-6 font-medium text-gray-900 dark:text-white">
              Stock Analysis
            </h3>
            <p className="mt-1 max-w-2xl text-sm text-gray-500 dark:text-gray-400">
              Select analysis type and upload a stock market graph for AI analysis.
            </p>
          </div>
          
          <div className="border-t border-gray-200 dark:border-gray-700">
            <form onSubmit={handleSubmit} className="px-4 py-5 sm:p-6">
              {/* Step 1: Select Analysis Type */}
              <div className="mb-8">
                <h4 className="text-md font-medium text-gray-900 dark:text-white mb-4">
                  Step 1: Select Analysis Type
                </h4>
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                  {(['Intraday Trading', 'Positional Trading', 'Swing Trading'] as AnalysisType[]).map((type) => (
                    <div 
                      key={type}
                      className={`border rounded-lg p-4 cursor-pointer transition-all ${analysisType === type ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20' : 'hover:border-gray-300 dark:hover:border-gray-600'}`}
                      onClick={() => handleAnalysisTypeSelect(type)}
                    >
                      <h5 className="font-medium text-gray-900 dark:text-white">{type}</h5>
                      <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                        Price: ${pricing[type]}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
              
              {/* Step 2: Upload Stock Graph */}
              <div className="mb-8">
                <h4 className="text-md font-medium text-gray-900 dark:text-white mb-4">
                  Step 2: Upload Stock Market Graph
                </h4>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 dark:border-gray-700 border-dashed rounded-md">
                  <div className="space-y-1 text-center">
                    {preview ? (
                      <div className="flex flex-col items-center">
                        <Image src={preview} alt="Preview" className="max-h-64 mb-4" width={400} height={300} />
                        <button
                          type="button"
                          onClick={() => {
                            setFile(null);
                            setPreview('');
                          }}
                          className="text-sm text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-300"
                        >
                          Remove image
                        </button>
                      </div>
                    ) : (
                      <>
                        <svg
                          className="mx-auto h-12 w-12 text-gray-400"
                          stroke="currentColor"
                          fill="none"
                          viewBox="0 0 48 48"
                          aria-hidden="true"
                        >
                          <path
                            d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                            strokeWidth={2}
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          />
                        </svg>
                        <div className="flex text-sm text-gray-600 dark:text-gray-400">
                          <label
                            htmlFor="file-upload"
                            className="relative cursor-pointer bg-white dark:bg-gray-800 rounded-md font-medium text-blue-600 dark:text-blue-400 hover:text-blue-500 dark:hover:text-blue-300 focus-within:outline-none"
                          >
                            <span>Upload a file</span>
                            <input
                              id="file-upload"
                              name="file-upload"
                              type="file"
                              className="sr-only"
                              accept="image/*"
                              onChange={handleFileChange}
                            />
                          </label>
                          <p className="pl-1">or drag and drop</p>
                        </div>
                        <p className="text-xs text-gray-500 dark:text-gray-400">
                          PNG, JPG, GIF up to 10MB
                        </p>
                      </>
                    )}
                  </div>
                </div>
              </div>
              
              {/* Error Message */}
              {error && (
                <div className="mb-4 text-sm text-red-600 dark:text-red-400">
                  {error}
                </div>
              )}
              
              {/* Submit Button */}
              <div className="flex justify-end">
                <button
                  type="submit"
                  disabled={loading || !analysisType || !file}
                  className={`inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white ${loading || !analysisType || !file ? 'bg-gray-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700'}`}
                >
                  {loading ? (
                    <>
                      <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Processing...
                    </>
                  ) : (
                    'Submit for Analysis'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
    </div>
  );
};

// Main page with UserLayout wrapper
const AnalysisPage: React.FC = () => {
  return (
    <UserLayout>
      <AnalysisPageContent />
    </UserLayout>
  );
};

export default AnalysisPage;