'use client'

import { useState } from 'react';
import { useRouter, redirect } from 'next/navigation';
import { useAuth } from '@/hooks/use-auth';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import Input from '@/components/ui/Input';
import UserLayout from '@/components/UserLayout';

type AnalysisType = 'Intraday Trading' | 'Positional Trading' | 'Swing Trading';

const NewAnalysisPageContent: React.FC = () => {
  const router = useRouter();
  const { user } = useAuth();
  const [analysisType, setAnalysisType] = useState<AnalysisType | null>(null);
  const [stockName, setStockName] = useState<string>('');
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');
  const [preview, setPreview] = useState<string>('');
  const [success, setSuccess] = useState<boolean>(false);
  const [newAnalysisId, setNewAnalysisId] = useState<string>('');
  
  // Pricing for different analysis types
  const pricing = {
    'Intraday Trading': 10,
    'Positional Trading': 15,
    'Swing Trading': 20
  };
  
  if (!user && typeof window !== 'undefined') {
    // Use router.push() for client-side redirect
    router.push('/login');
    return null;
  }
  
  if (!user) {
    // For server-side redirect
    redirect('/login');
  }
  
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      // Check if file is an image
      if (!selectedFile.type.startsWith('image/')) {
        setError('Please upload an image file');
        setFile(null);
        setPreview('');
        return;
      }
      
      setFile(selectedFile);
      setError('');
      
      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setPreview(e.target?.result as string);
      };
      reader.readAsDataURL(selectedFile);
    }
  };
  
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!analysisType) {
      setError('Please select an analysis type');
      return;
    }
    
    if (!file) {
      setError('Please upload a stock market graph image');
      return;
    }
    
    if (!stockName.trim()) {
      setError('Please enter a stock name');
      return;
    }
    
    setLoading(true);
    setError('');
    setSuccess(false);
    
    try {
      // In a real implementation, this would upload the file to a server
      // and process the analysis with AI
      
      // For now, we'll simulate the process with localStorage
      if (typeof window !== 'undefined') {
        const storedData = localStorage.getItem('stock_analysis_db');
        if (storedData) {
          const parsedData = JSON.parse(storedData);
          const currentUserIndex = parsedData.users.findIndex((u: { id: string }) => u.id === user?.id);
          
          if (currentUserIndex !== -1) {
            const currentUser = parsedData.users[currentUserIndex];
            
            // Check if user has access
            const hasTrialAccess = currentUser.analysis_count < 5;
            const hasWalletBalance = currentUser.wallet_balance >= pricing[analysisType];
            
            if (!hasTrialAccess && !hasWalletBalance) {
              setError('You have no access to analysis. Please top up your wallet.');
              setLoading(false);
              return;
            }
            
            // Deduct from wallet if trial is exhausted
            if (!hasTrialAccess && hasWalletBalance) {
              parsedData.users[currentUserIndex].wallet_balance -= pricing[analysisType];
            }
            
            // Increment analysis count
            parsedData.users[currentUserIndex].analysis_count += 1;
            
            // Create a new analysis entry
            const newAnalysis = {
              id: `analysis_${Date.now()}`,
              analysis_type: analysisType,
              stock_name: stockName.trim(),
              analysis_result: 'This is a sample analysis result. In a real application, this would be generated by AI based on the uploaded image.',
              image_path: preview, // In a real app, this would be a path to the stored image
              created_at: new Date().toISOString()
            };
            
            // Add to user's analysis history
            if (!parsedData.users[currentUserIndex].analysis_history) {
              parsedData.users[currentUserIndex].analysis_history = [];
            }
            parsedData.users[currentUserIndex].analysis_history.unshift(newAnalysis);
            
            // Save updated data
            localStorage.setItem('stock_analysis_db', JSON.stringify(parsedData));
            
            setNewAnalysisId(newAnalysis.id);
            setSuccess(true);
            
            // Redirect to the new analysis after a short delay
            setTimeout(() => {
              router.push(`/analysis/${newAnalysis.id}`);
            }, 2000);
          } else {
            setError('User not found');
          }
        } else {
          setError('Database not initialized');
        }
      }
    } catch (err) {
      setError('Failed to process analysis');
      console.error('Error processing analysis:', err);
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <div className="container mx-auto py-6 sm:px-6 lg:px-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">New Analysis</h1>
        <Button onClick={() => router.push('/dashboard')} variant="secondary">
          Back to Dashboard
        </Button>
      </div>
      
      {success ? (
        <div className="max-w-2xl mx-auto text-center py-16">
          <h2 className="text-2xl font-bold text-green-600 mb-4">Analysis Submitted Successfully!</h2>
          <p className="text-muted-foreground mb-8">
            Your analysis is being processed. You will be redirected to the results shortly.
          </p>
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600 mx-auto mb-8"></div>
          <Button 
            onClick={() => router.push(`/analysis/${newAnalysisId}`)}
            disabled={loading}
          >
            View Analysis Now
          </Button>
        </div>
      ) : (
        <Card className="p-6 max-w-2xl mx-auto">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <h2 className="text-xl font-bold mb-4">Create a New Stock Analysis</h2>
              <p className="text-muted-foreground">
                Upload a stock market graph image and select an analysis type to get AI-powered insights.
              </p>
            </div>
            
            <Separator />
            
            <div className="space-y-4">
              <div>
                <Label htmlFor="stockName" className="text-base font-medium">
                  Stock Name
                </Label>
                <Input
                  id="stockName"
                  value={stockName}
                  onChange={(e) => setStockName(e.target.value)}
                  placeholder="Enter the name of the stock"
                  className="mt-1"
                />
              </div>
              
              <div>
                <Label className="text-base font-medium block mb-2">
                  Analysis Type
                </Label>
                <div className="space-y-3">
                  <div className="flex items-center space-x-2 border rounded-lg p-3 cursor-pointer hover:border-primary transition-colors">
                    <input 
                      type="radio" 
                      name="analysisType" 
                      value="Intraday Trading" 
                      id="intraday" 
                      checked={analysisType === 'Intraday Trading'}
                      onChange={(e) => setAnalysisType(e.target.value as AnalysisType)}
                      className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary"
                    />
                    <Label htmlFor="intraday" className="cursor-pointer flex-1">
                      <div className="font-medium">Intraday Trading</div>
                      <div className="text-sm text-muted-foreground">Analysis for day trading strategies</div>
                    </Label>
                    <div className="font-semibold">${pricing['Intraday Trading']}</div>
                  </div>
                  
                  <div className="flex items-center space-x-2 border rounded-lg p-3 cursor-pointer hover:border-primary transition-colors">
                    <input 
                      type="radio" 
                      name="analysisType" 
                      value="Positional Trading" 
                      id="positional" 
                      checked={analysisType === 'Positional Trading'}
                      onChange={(e) => setAnalysisType(e.target.value as AnalysisType)}
                      className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary"
                    />
                    <Label htmlFor="positional" className="cursor-pointer flex-1">
                      <div className="font-medium">Positional Trading</div>
                      <div className="text-sm text-muted-foreground">Analysis for multi-day trading positions</div>
                    </Label>
                    <div className="font-semibold">${pricing['Positional Trading']}</div>
                  </div>
                  
                  <div className="flex items-center space-x-2 border rounded-lg p-3 cursor-pointer hover:border-primary transition-colors">
                    <input 
                      type="radio" 
                      name="analysisType" 
                      value="Swing Trading" 
                      id="swing" 
                      checked={analysisType === 'Swing Trading'}
                      onChange={(e) => setAnalysisType(e.target.value as AnalysisType)}
                      className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary"
                    />
                    <Label htmlFor="swing" className="cursor-pointer flex-1">
                      <div className="font-medium">Swing Trading</div>
                      <div className="text-sm text-muted-foreground">Analysis for multi-week trading strategies</div>
                    </Label>
                    <div className="font-semibold">${pricing['Swing Trading']}</div>
                  </div>
                </div>
              </div>
              
              <div>
                <Label className="text-base font-medium block mb-2">
                  Upload Stock Chart Image
                </Label>
                <div className="flex flex-col space-y-2">
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileChange}
                    className="border rounded-lg p-3 text-sm text-gray-500
                      file:mr-4 file:py-2 file:px-4
                      file:rounded-md file:border-0
                      file:text-sm file:font-medium
                      file:bg-primary file:text-primary-foreground
                      hover:file:bg-primary/90"
                  />
                  {preview && (
                    <div className="mt-2 rounded-lg overflow-hidden border">
                      <img 
                        src={preview} 
                        alt="Stock chart preview" 
                        className="max-w-full h-auto max-h-[300px] object-contain"
                      />
                    </div>
                  )}
                </div>
              </div>
            </div>
            
            {error && (
              <div className="bg-destructive/10 text-destructive border border-destructive/20 rounded-lg p-4">
                {error}
              </div>
            )}
            
            <div className="flex justify-between items-center">
              <Button type="button" variant="secondary" onClick={() => router.push('/dashboard')}>
                Cancel
              </Button>
              <Button type="submit" disabled={loading} className="bg-primary">
                {loading ? 'Processing...' : 'Submit for Analysis'}
              </Button>
            </div>
          </form>
        </Card>
      )}
    </div>
  );
};

// Main page with UserLayout wrapper
const NewAnalysisPage: React.FC = () => {
  return (
    <UserLayout>
      <NewAnalysisPageContent />
    </UserLayout>
  );
};

export default NewAnalysisPage;